### ISSUE TITLE
mostSigBits and leastSigBits

### ISSUE THREAD

**Issue by lenn1024** [melezov/scala-uuid#1]
Hi! what does mostSigBits and leastSigBits  mean?
Do they unique like uuid?

**Comment by melezov** [comment]
They are simply proxies to [`getLeastSignificantBits()`](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#getLeastSignificantBits) and [`getMostSignificantBits()`](https://docs.oracle.com/javase/8/docs/api/java/util/UUID.html#getMostSignificantBits).

The reason why they are named `mostSigBits` and `leastSigBits` is because these are the [actual names](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/UUID.java#l82) of the underlying primitive fields in which the UUID object stores its 128 bit value.
